name: Nightly Builds

on: [push, pull_request]

jobs:
  Linux:
    # AppImages should be built on the oldest possible version.
    # This should also match the version referenced in AppImage.yml.
    runs-on: ubuntu-20.04

    steps:

    - name: Git Clone
      uses: actions/checkout@v4.1.6

    - name: Update Repositories
      run: sudo apt-get update
    - name: Install Build Dependencies
      run: |
        # NOTE: The version from LuaRocks is just as old.
        sudo apt-get install -y rename lua-ldoc make

    - name: Build AppImage
      run: |
        wget -O pkg2appimage.AppImage \
                "https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage--x86_64.AppImage"
        chmod +x pkg2appimage.AppImage
        ./pkg2appimage.AppImage AppImage.yml
        cd out
        rename 's/.*\.glibc/Applause-nightly-glibc/' *.AppImage
        chmod a+x *.AppImage
    - name: Archive AppImage
      uses: pyTooling/Actions/releaser@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        rm: true
        files: out/*.AppImage

    - name: Build Lua Documentation
      run: |
        make doc
    - name: Publish Website
      run: |
        cd doc
        touch .nojekyll
        git init
        cp ../.git/config ./.git/config
        git add .
        git config --local user.email "Website@GitHubActions"
        git config --local user.name "GitHub Actions"
        git commit -a -m "update ${{ github.sha }}"
        git push -u origin +HEAD:gh-pages
